Repository nhn/tui.editor, pull requests merged in 2020-09, with the labels that each got.

#1171 feat: add front matter
  apps/editor/index.d.ts
  apps/editor/src/js/convertor.js
  apps/editor/src/js/editor.js
  apps/editor/src/js/htmlRenderConvertors.js
  apps/editor/src/js/markdownToHTML.js
  apps/editor/src/js/mdPreview.js
  apps/editor/test/unit/editor.spec.js
  libs/toastmark/src/__test__/toastmark.spec.ts
  libs/toastmark/src/commonmark/blocks.ts
  libs/toastmark/src/commonmark/frontMatter/__test__/frontMatter.spec.ts
  libs/toastmark/src/commonmark/frontMatter/helper.ts
  libs/toastmark/src/commonmark/frontMatter/parser.ts
  libs/toastmark/src/commonmark/inlines.ts
  libs/toastmark/src/commonmark/node.ts
  libs/toastmark/src/html/baseConvertors.ts
  libs/toastmark/src/html/render.ts
  libs/toastmark/src/nodeHelper.ts
  libs/toastmark/src/toastmark.ts
Labels: Feature

#1207 fix: Improved norwegian translations
  apps/editor/src/js/i18n/nb-no.js
  plugins/table-merged-cell/src/js/langs.js
Labels: Enhancement

#1208 feat: add link to image correctly
  apps/editor/src/css/contents.css
  apps/editor/src/css/editor.css
  apps/editor/src/css/old/contents.css
  apps/editor/src/css/old/editor.css
  apps/editor/src/js/markdownCommands/addLink.js
  apps/editor/src/js/ui/popupAddLink.js
  apps/editor/src/js/utils/dom.js
  apps/editor/src/js/viewer.js
  apps/editor/src/js/wwLinkManager.js
  apps/editor/src/js/wwTaskManager.js
  apps/editor/src/js/wysiwygCommands/addLink.js
  apps/editor/src/js/wysiwygEditor.js
  apps/editor/test/unit/markdownCommands/addLink.spec.js
  apps/editor/test/unit/ui/popupAddLink.spec.js
  apps/editor/test/unit/wysiwygCommands/addLink.spec.js
Labels: Enhancement, Mode: Markdown, Mode: WYSIWYG
