Repository nhn/tui.editor, pull requests merged in 2020-08, with the labels that each got.

#1126 feat: add key action to table in markdown
  apps/editor/package-lock.json
  apps/editor/package.json
  apps/editor/src/js/editor.js
  apps/editor/src/js/markdownCommands/addLine.js
  apps/editor/src/js/markdownCommands/changeTaskMarker.js
  apps/editor/src/js/markdownCommands/moveNextCursorOrIndent.js
  apps/editor/src/js/markdownCommands/movePrevCursorOrOutdent.js
  apps/editor/src/js/markdownCommands/toggleTaskMarker.js
  apps/editor/src/js/markdownEditor.js
  apps/editor/src/js/utils/markdown.js
  apps/editor/test/unit/markdownCommands/addLine.spec.js
  apps/editor/test/unit/markdownCommands/changeTaskMarker.spec.js
  apps/editor/test/unit/markdownCommands/moveNextCursorOrIndent.spec.js
  apps/editor/test/unit/markdownCommands/movePrevCursorOrOutdent.spec.js
  apps/editor/test/unit/markdownCommands/toggleTaskMarker.spec.js
  apps/editor/test/unit/markdownEditor.spec.js
Labels: Feature, Mode: Markdown, NHN, TOAST UI

#1162 feat: i18n hr-HR
  README.md
  apps/editor/src/js/i18n/hr-hr.js
  plugins/table-merged-cell/src/js/langs.js
Labels: Feature, Plugin: Table Merged Cell, TOAST UI

#1164 fix: broken type of plugin option when using table-merged-cell plugin (fix #1160)
  apps/editor/index.d.ts
Labels: Bug

#1163 feat: init disabled task in viewer
  apps/editor/src/js/viewer.js
Labels: Category: List, Feature

#1168 fix: fenced code block is broken depending on input order (fix #1167)
  apps/editor/src/js/codemirror/continuelist.js
  libs/toastmark/src/__test__/toastmark.spec.ts
  libs/toastmark/src/toastmark.ts
Labels: Bug
